#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --job-name=batch11_bcl2fastq.job
#SBATCH --cpus-per-task=6
#SBATCH --time=11:00:00
#SBATCH --mem=32GB
#SBATCH --array=1
#SBATCH --output=0.batch11_bcl2fastq_newcovid19.out

module load gcc
module load intel
module load bcl2fastq2

bcl2fastq \
  --barcode-mismatches 0 \
  --no-lane-splitting \
  -R res_bcl2fastq/batch11/210121_A00308_0067_AH7H5CDMXX/ \
  --sample-sheet res_bcl2fastq/WES_Covid_Batch_11_JJ.csv 
  -r 6 -p 6 -w 6 \
  -o res_bcl2fastq/batch11/
