#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --job-name=3.11_gatk_newcovid19
#SBATCH --cpus-per-task=1
#SBATCH --time=12:00:00
#SBATCH --mem=12GB
#SBATCH --array=1-96
#SBATCH --output=3.batch11_gatk_newcovid19-%A_%a

i=$SLURM_ARRAY_TASK_ID
srr=$(sed -n $i'p' res_bcl2fastq/batch11_list.txt)

module load gcc
module load jdk

mkdir -p res_gatk4_newcovid19/batch11_res_gatk4_newcovid19/${srr}/

# GATK hg38 files: https://console.cloud.google.com/storage/browser/genomics-public-data/resources/broad/hg38/v0;tab=objects?prefix=&forceOnObjectsSortingFiltering=false
echo "####################################"
date
echo "Base Quality Score Recalibration"
echo "####################################"

tools_newcovid19/gatk-4.2.0.0/gatk BaseRecalibrator \
  --tmp-dir res_gatk4_newcovid19/tmp/ \
  --input res_mapping_newcovid19/batch11_res_mapping_newcovid19/${srr}/${srr}_dedup_batch11.bam \
  -R ref_dat/ref_gatk_newcovid19/Homo_sapiens_assembly38.fasta \
  --known-sites ref_dat/ref_gatk_newcovid19/Homo_sapiens_assembly38.dbsnp138.vcf \
  --known-sites ref_dat/ref_gatk_newcovid19/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz \
  --known-sites ref_dat/ref_gatk_newcovid19/Homo_sapiens_assembly38.known_indels.vcf.gz \
  -O res_gatk4_newcovid19/batch11_res_gatk4_newcovid19/${srr}/${srr}_recal_batch11.table \


echo "####################################"
date
echo "Base Quality Score Binning Scheme"
echo "####################################"


tools_newcovid19/gatk-4.2.0.0/gatk ApplyBQSR \
  --tmp-dir res_gatk4_newcovid19/tmp/ \
  -I res_mapping_newcovid19/batch11_res_mapping_newcovid19/${srr}/${srr}_dedup_batch11.bam \
  -O res_gatk4_newcovid19/batch11_res_gatk4_newcovid19/${srr}/${srr}_recal_batch11.bam \
  -bqsr res_gatk4_newcovid19/batch11_res_gatk4_newcovid19/${srr}/${srr}_recal_batch11.table \
  -R ref_dat/ref_gatk_newcovid19/Homo_sapiens_assembly38.fasta \
  --static-quantized-quals 10 --static-quantized-quals 20 --static-quantized-quals 30

 
echo "####################################"
date
echo "Haplotype Caller"
echo "####################################"


tools_newcovid19/gatk-4.2.0.0/gatk HaplotypeCaller \
  --tmp-dir res_gatk4_newcovid19/tmp/ \
  -R ref_dat/ref_gatk_newcovid19/Homo_sapiens_assembly38.fasta \
  -I res_gatk4_newcovid19/batch11_res_gatk4_newcovid19/${srr}/${srr}_recal_batch11.bam \
  -O res_gatk4_newcovid19/batch11_res_gatk4_newcovid19/${srr}/${srr}_batch11.g.vcf.gz \
  -ERC GVCF \
  -G StandardAnnotation -G StandardHCAnnotation -G AS_StandardAnnotation 
